name: Cortex-RTOS CI

on:
    push:
        branches: ["main", "dev", "feature/**"]
    pull_request:
        branches: ["main", "dev"]

jobs:
    build:
        runs-on: self-hosted
        timeout-minutes: 10
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Build Docker Image
          run: docker build -t cortex-rtos-ci .
        
        - name: Compile Kernel
          run : docker run --rm cortex-rtos-ci make all

        - name: Run Kernel
          run: |
            timeout 10 docker run --rm cortex-rtos-ci || 
              if [$? -eq 124];
                then echo "Kernel ran successfully for 10 seconds and was terminated.";
                exit 0;
              else 
                exit 1;
            fi